# Generated by Django 5.2.7 on 2026-01-09 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Food", "Food"),
                            ("Travel", "Travel"),
                            ("Shopping", "Shopping"),
                            ("Bills", "Bills"),
                        ],
                        max_length=50,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("description", models.TextField()),
                (
                    "payment_mode",
                    models.CharField(
                        choices=[("Cash", "Cash"), ("Card", "Card"), ("UPI", "UPI")],
                        max_length=20,
                    ),
                ),
                ("merchant_name", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=100)),
                ("notes", models.TextField(blank=True)),
                ("created_by", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
