# Generated by Django 5.2.7 on 2026-01-09 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="category",
            field=models.CharField(
                choices=[
                    ("Food", "Food"),
                    ("Travel", "Travel"),
                    ("Shopping", "Shopping"),
                    ("Bills", "Bills"),
                    ("Other", "Other"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="payment_mode",
            field=models.CharField(
                choices=[
                    ("Cash", "Cash"),
                    ("Card", "Card"),
                    ("UPI", "UPI"),
                    ("Paytm", "Paytm"),
                ],
                max_length=20,
            ),
        ),
    ]
